export interface DadJoke {
  setup: string;
  punchline: string;
}

export const dadJokes: DadJoke[] = [
  { setup: "Why don't scientists trust atoms?", punchline: "Because they make up everything!" },
  { setup: "What do you call a robot that takes the long way around?", punchline: "R2-Detour!" },
  { setup: "Why did the lab equipment go to therapy?", punchline: "It had too many issues!" },
  { setup: "How does a scientist freshen their breath?", punchline: "With experi-mints!" },
  { setup: "Why can't you trust atoms in the lab?", punchline: "They make up literally everything!" },
  { setup: "What did the DNA say to the other DNA?", punchline: "Do these genes make me look fat?" },
  { setup: "Why did the robot go on a diet?", punchline: "It had too many bytes!" },
  { setup: "What do you call a microbiologist who travels?", punchline: "A staph infection!" },
  { setup: "Why did the germ cross the microscope?", punchline: "To get to the other slide!" },
  { setup: "What's a robot's favorite type of music?", punchline: "Heavy metal!" },
  { setup: "Why don't bacteria ever go to school?", punchline: "They always get expelled!" },
  { setup: "What do you call a lab coat that never gets dirty?", punchline: "An impasta!" },
  { setup: "Why was the math book sad in the lab?", punchline: "It had too many problems!" },
  { setup: "What did one petri dish say to the other?", punchline: "You've got me covered!" },
  { setup: "Why did the equipment break up with the robot?", punchline: "It needed some space!" },
  { setup: "What do you call a bear in the lab?", punchline: "A bear-ometer!" },
  { setup: "Why was the microscope always calm?", punchline: "It had great focus!" },
  { setup: "What's a robot's favorite snack?", punchline: "Computer chips!" },
  { setup: "Why did the lab technician bring a ladder?", punchline: "To reach new heights in research!" },
  { setup: "What do you call a funny molecule?", punchline: "A silly-con!" },
  { setup: "Why don't skeletons work in labs?", punchline: "They don't have the guts!" },
  { setup: "What did the biologist wear to impress?", punchline: "Designer genes!" },
  { setup: "Why was the chemistry book always stressed?", punchline: "It had too many solutions to find!" },
  { setup: "What do you call a robot that likes to clean?", punchline: "A vacuum cleaner!" },
  { setup: "Why did the scientist install a knocker on the lab door?", punchline: "To win the No-bell prize!" },
  { setup: "What's a bacteria's favorite game?", punchline: "Cells and ladders!" },
  { setup: "Why did the DNA go to the gym?", punchline: "To get ripped!" },
  { setup: "What do you call a lab with no windows?", punchline: "A cell!" },
  { setup: "Why was the robot so good at yoga?", punchline: "It had great flexibility in its programming!" },
  { setup: "What did the thermometer say to the graduated cylinder?", punchline: "You may have graduated, but I have more degrees!" },
  { setup: "Why don't cells ever get lost?", punchline: "They always have their GPS - their Golgi Positioning System!" },
  { setup: "What's a robot's favorite exercise?", punchline: "Circuit training!" },
  { setup: "Why did the equipment go to the doctor?", punchline: "It was feeling a bit run down!" },
  { setup: "What do you call a singing robot?", punchline: "A-dell!" },
  { setup: "Why was the lab always cold?", punchline: "It was full of drafts!" },
  { setup: "What did the scientist say when they found two isotopes of helium?", punchline: "HeHe!" },
  { setup: "Why don't robots ever get tired?", punchline: "They have unlimited battery in their enthusiasm!" },
  { setup: "What's a lab technician's favorite type of tree?", punchline: "A chemis-tree!" },
  { setup: "Why did the cell phone go to the lab?", punchline: "It needed to get its cell-f checked!" },
  { setup: "What do you call a robot that always tells the truth?", punchline: "Frank-enstein!" },
  { setup: "Why was the lab equipment always happy?", punchline: "It had a positive outlook!" },
  { setup: "What did the beaker say to the flask?", punchline: "You crack me up!" },
  { setup: "Why don't scientists like doors?", punchline: "Because they're always getting in the way of their experiments!" },
  { setup: "What's a robot's favorite dance?", punchline: "The robot!" },
  { setup: "Why did the biology teacher break up with the physics teacher?", punchline: "There was no chemistry!" },
  { setup: "What do you call a lab safety manual?", punchline: "A safety-net!" },
  { setup: "Why was the computer cold in the lab?", punchline: "It left its Windows open!" },
  { setup: "What did one ion say to the other?", punchline: "I've got my ion you!" },
  { setup: "Why don't bacteria go to parties?", punchline: "They always split early!" },
  { setup: "What's a scientist's favorite dog breed?", punchline: "A Lab-rador!" },
  { setup: "Why did the robot go to art school?", punchline: "To improve its interface design!" },
  { setup: "What do you call a lab that's always messy?", punchline: "A hazard-ous waste!" },
  { setup: "Why was the microscope bad at keeping secrets?", punchline: "It always magnified things!" },
  { setup: "What did the scientist name their dog?", punchline: "Lab-rador Retriever!" },
  { setup: "Why don't robots ever get cold?", punchline: "They wear their thermal jackets!" },
  { setup: "What's a chemist's favorite type of dog?", punchline: "A lab!" },
  { setup: "Why did the lab equipment join a band?", punchline: "It wanted to be instrumental!" },
  { setup: "What do you call a robot with good manners?", punchline: "A civil engineer!" },
  { setup: "Why was the centrifuge always dizzy?", punchline: "It kept going in circles!" },
  { setup: "What did the mitochondria say to the cell?", punchline: "I'm the powerhouse around here!" },
  { setup: "Why don't scientists play hide and seek?", punchline: "Good luck hiding when someone has a microscope!" },
  { setup: "What's a robot's favorite board game?", punchline: "Circuit breakers!" },
  { setup: "Why did the lab coat go to school?", punchline: "To get a degree!" },
  { setup: "What do you call a nervous robot?", punchline: "A worry-bot!" },
  { setup: "Why was the bunsen burner so popular?", punchline: "It was always lit!" },
  { setup: "What did the science book say to the math book?", punchline: "I've got way more solutions!" },
  { setup: "Why don't viruses ever feel lonely?", punchline: "They're always surrounded by hosts!" },
  { setup: "What's a robot's favorite season?", punchline: "Spring - they love a good reboot!" },
  { setup: "Why did the microscope go to the party?", punchline: "To see what's going on!" },
  { setup: "What do you call a lazy robot?", punchline: "A pro-crash-tinator!" },
  { setup: "Why was the lab notebook always full?", punchline: "It had too many notes to take!" },
  { setup: "What did the scientist wear on Halloween?", punchline: "A lab-coat of arms!" },
  { setup: "Why don't cells ever argue?", punchline: "They always reach a consensus!" },
  { setup: "What's a robot's favorite movie?", punchline: "The Terminater - wait, that's scary!" },
  { setup: "Why did the graduated cylinder fail its test?", punchline: "It couldn't measure up!" },
  { setup: "What do you call smart bacteria?", punchline: "Multi-cultural!" },
  { setup: "Why was the lab always organized?", punchline: "Everything had its proper place-bo!" },
  { setup: "What did the robot say to the vending machine?", punchline: "You're my type!" },
  { setup: "Why don't scientists ever get bored?", punchline: "They always have something to experiment with!" },
  { setup: "What's a lab technician's favorite sport?", punchline: "Beaker-ball!" },
  { setup: "Why did the equipment refuse to work?", punchline: "It needed a break!" },
  { setup: "What do you call a robot that's always late?", punchline: "Pro-crash-tinating!" },
  { setup: "Why was the periodic table so confident?", punchline: "It knew all the elements of success!" },
  { setup: "What did one cell say to its sister cell?", punchline: "Mitosis!" },
  { setup: "Why don't robots sleep?", punchline: "They're always wired!" },
  { setup: "What's a scientist's favorite type of music?", punchline: "Lab-step!" },
  { setup: "Why did the lab safety goggles break up?", punchline: "They couldn't see eye to eye!" },
  { setup: "What do you call a robot comedian?", punchline: "A laugh-bot!" },
  { setup: "Why was the pH meter always neutral?", punchline: "It didn't take sides!" },
  { setup: "What did the scientist say when they finally solved the problem?", punchline: "Eureka! I mean, You-reek-a!" },
  { setup: "Why don't enzymes ever get stressed?", punchline: "They know how to break things down!" },
  { setup: "What's a robot's favorite ice cream?", punchline: "Nuts and bolts!" },
  { setup: "Why did the lab equipment go to the gym?", punchline: "To work on its core!" },
  { setup: "What do you call a philosophical robot?", punchline: "Deep-thought 2.0!" },
  { setup: "Why was the autoclave always so hot?", punchline: "It was under a lot of pressure!" },
  { setup: "What did the bacteria say to the antibiotic?", punchline: "You're cramping my style!" },
  { setup: "Why don't robots ever forget?", punchline: "They have backup memory!" },
  { setup: "What's a scientist's favorite candy?", punchline: "Experi-mints!" },
  { setup: "Why did the lab door always complain?", punchline: "Everyone kept pushing its buttons!" },
  { setup: "What do you call a happy robot?", punchline: "An opti-bot!" },
  { setup: "Why was the lab fridge always full?", punchline: "It had culture!" },
  { setup: "What did the scientist say to motivate the lab?", punchline: "Let's get this reaction started!" },
  { setup: "Why don't pipettes ever gossip?", punchline: "They don't like to spread things around!" },
  { setup: "What's a robot's favorite holiday?", punchline: "Labor Day!" },
  { setup: "Why did the test tube go to school?", punchline: "To get a little more cultured!" },
  { setup: "What do you call a romantic robot?", punchline: "A love-bot!" },
  { setup: "Why was the lab so noisy?", punchline: "Everyone was making sound hypotheses!" },
  { setup: "What did the hydrogen atom say?", punchline: "I've lost my electron! Are you positive?" },
  { setup: "Why don't robots play cards?", punchline: "Too many chips on the table!" },
  { setup: "What's a microbiologist's favorite game?", punchline: "Germ-an board games!" },
  { setup: "Why did the lab bench feel important?", punchline: "Everything revolved around it!" },
  { setup: "What do you call a musical robot?", punchline: "An iPod!" },
  { setup: "Why was the scientific method so popular?", punchline: "It had a systematic approach to everything!" },
  { setup: "What did the cell membrane say?", punchline: "I'm so selective!" },
  { setup: "Why don't robots write with pencils?", punchline: "They prefer to type!" },
  { setup: "What's a lab technician's favorite vegetable?", punchline: "Lab-bage!" },
  { setup: "Why did the equipment feel accomplished?", punchline: "It finally met its calibration!" },
  { setup: "What do you call a robot detective?", punchline: "Sherlock Ohms!" },
  { setup: "Why was the lab coat always white?", punchline: "It wanted to reflect on things!" },
  { setup: "What did the scientist say when the experiment worked?", punchline: "That's how we roll... in the lab!" },
  { setup: "Why don't bacteria ever win races?", punchline: "They're always splitting at the finish line!" },
  { setup: "What's a robot's favorite subject?", punchline: "Geometry - it's all about the angles!" },
  { setup: "Why did the lab timer go to therapy?", punchline: "It had too much time on its hands!" },
  { setup: "What do you call a scared robot?", punchline: "A chicken-bot!" },
  { setup: "Why was the lab always well-lit?", punchline: "It had brilliant ideas!" },
  { setup: "What did the protein say at the gym?", punchline: "Time to get folded!" },
  { setup: "Why don't robots ever get hungry?", punchline: "They run on energy!" },
  { setup: "What's a scientist's favorite fruit?", punchline: "Lab-berries!" },
  { setup: "Why did the safety shower feel important?", punchline: "It was the first responder!" },
  { setup: "What do you call an artistic robot?", punchline: "A draw-bot!" },
  { setup: "Why was the lab notebook never lonely?", punchline: "It was full of notes!" },
  { setup: "What did the microscope slide say?", punchline: "I'm under a lot of pressure!" },
  { setup: "Why don't cells use social media?", punchline: "They prefer cell-to-cell communication!" },
  { setup: "What's a robot's favorite drink?", punchline: "Java!" },
  { setup: "Why did the lab equipment win an award?", punchline: "For outstanding performance!" },
  { setup: "What do you call a polite robot?", punchline: "Well-programmed!" },
  { setup: "Why was the incubator always warm?", punchline: "It had a nurturing personality!" },
  { setup: "What did the lab say to the new equipment?", punchline: "Welcome to the bench!" },
  { setup: "Why don't chromosomes ever get lost?", punchline: "They always pair up!" },
  { setup: "What's a robot's favorite game?", punchline: "Hide and beep!" },
  { setup: "Why did the flask feel empty?", punchline: "It needed to be filled in!" },
  { setup: "What do you call a sleepy robot?", punchline: "A nap-bot!" },
  { setup: "Why was the lab always prepared?", punchline: "It had contingency plans!" },
  { setup: "What did the scientist name their clone?", punchline: "Themselves 2.0!" },
  { setup: "Why don't electrons ever travel alone?", punchline: "They like to stay current!" },
  { setup: "What's a robot's favorite type of bread?", punchline: "Circuit rolls!" },
  { setup: "Why did the lab scale feel balanced?", punchline: "It knew how to weigh its options!" },
  { setup: "What do you call a dancing robot?", punchline: "A groove-bot!" },
  { setup: "Why was the fume hood always on?", punchline: "It wanted to clear the air!" },
  { setup: "What did the lab say about teamwork?", punchline: "We're all in this beaker together!" },
  { setup: "Why don't ribosomes ever stop working?", punchline: "They're always making protein!" },
  { setup: "What's a robot's favorite restaurant?", punchline: "The Hard Drive Cafe!" },
  { setup: "Why did the lab manual look tired?", punchline: "It had been read cover to cover!" },
  { setup: "What do you call a helpful robot?", punchline: "An assist-ant!" },
  { setup: "Why was the control group always calm?", punchline: "Nothing was testing it!" },
  { setup: "What did the scientist say to their coffee?", punchline: "Thanks for being my solution!" },
  { setup: "Why don't mitochondria ever stop?", punchline: "They're the powerhouse that never sleeps!" },
  { setup: "What's a robot's favorite weather?", punchline: "Cloud computing!" },
  { setup: "Why did the lab gloves feel protective?", punchline: "That was their purpose!" },
  { setup: "What do you call a wise robot?", punchline: "An AI-nstein!" },
  { setup: "Why was the lab always clean?", punchline: "It had a sterile personality!" },
  { setup: "What did the data say to the scientist?", punchline: "Analyze me!" },
  { setup: "Why don't viruses ever feel guilty?", punchline: "They have no cell-f awareness!" },
  { setup: "What's a robot's favorite room?", punchline: "The living room - they want to feel alive!" },
  { setup: "Why did the lab equipment take a vacation?", punchline: "It needed time to recharge!" },
  { setup: "What do you call a funny robot?", punchline: "A joke-bot 3000!" },
  { setup: "Why was the control always reliable?", punchline: "It was constant!" },
  { setup: "What did the beaker say to the scientist?", punchline: "I'm at your service!" },
  { setup: "Why don't amino acids ever argue?", punchline: "They know how to bond!" },
  { setup: "What's a robot's favorite vegetable?", punchline: "Silicon sprouts!" },
  { setup: "Why did the hypothesis feel confident?", punchline: "It was supported by evidence!" },
  { setup: "What do you call a fast robot?", punchline: "Quick-silver!" },
  { setup: "Why was the lab always secure?", punchline: "It had protocols in place!" },
  { setup: "What did the experiment say after success?", punchline: "I'm reproducible!" },
  { setup: "Why don't neurons ever forget?", punchline: "They have strong connections!" },
  { setup: "What's a robot's favorite book?", punchline: "The Manual!" },
  { setup: "Why did the petri dish feel crowded?", punchline: "Too many cultures!" },
  { setup: "What do you call a creative robot?", punchline: "An innov-ator!" },
  { setup: "Why was the lab bench always busy?", punchline: "It was the center of operations!" },
  { setup: "What did the scientist say about failure?", punchline: "It's just data in disguise!" },
  { setup: "Why don't lab coats ever get dirty?", punchline: "They're stain-resistant to criticism!" },
  { setup: "What's a robot's favorite time?", punchline: "Microseconds!" },
  { setup: "Why did the safety glasses feel important?", punchline: "They protected the vision!" },
  { setup: "What do you call a confused robot?", punchline: "A lost-bot!" },
  { setup: "Why was the lab always learning?", punchline: "Every experiment taught something new!" },
  { setup: "What did the equipment say about maintenance?", punchline: "Prevention is better than repair!" }
];

export const getRandomJoke = (): DadJoke => {
  return dadJokes[Math.floor(Math.random() * dadJokes.length)];
};
