import { Equipment, Booking, Project } from "./types";

export const mockProjects: Project[] = [
  {
    id: "p1",
    name: "Quantum Computing Research",
    description: "Advanced quantum computing experiments",
    color: "#fb6502",
  },
  {
    id: "p2",
    name: "Photonics Integration",
    description: "Photonic circuit integration and testing",
    color: "#00529b",
  },
  {
    id: "p3",
    name: "Neural Network Optimization",
    description: "Machine learning hardware optimization",
    color: "#50C878",
  },
  {
    id: "p4",
    name: "Material Characterization",
    description: "Advanced material testing and analysis",
    color: "#9370DB",
  },
];

export const mockEquipment: Equipment[] = [
  {
    id: "1",
    name: "Quantum Measurement System",
    type: "equipment",
    status: "available",
    location: "Dutton Lab - Room 101",
    description: "High-precision quantum state measurement",
    compatibleProjects: ["p1", "p2"],
  },
  {
    id: "2",
    name: "Photonic Probe Station",
    type: "equipment",
    status: "in-use",
    location: "Dutton Lab - Room 102",
    description: "Optical characterization and testing",
    compatibleProjects: ["p2", "p4"],
  },
  {
    id: "3",
    name: "Robotic Arm Alpha",
    type: "robot",
    status: "available",
    location: "Dutton Lab - Room 103",
    description: "6-axis precision robotic arm for sample handling",
    compatibleProjects: ["p1", "p3", "p4"],
  },
  {
    id: "4",
    name: "Cryogenic Testing Chamber",
    type: "equipment",
    status: "available",
    location: "Dutton Lab - Room 104",
    description: "Ultra-low temperature testing environment",
    compatibleProjects: ["p1"],
  },
  {
    id: "5",
    name: "Robotic Arm Beta",
    type: "robot",
    status: "maintenance",
    location: "Dutton Lab - Room 103",
    description: "High-speed automated testing robot",
    compatibleProjects: ["p2", "p3"],
  },
  {
    id: "6",
    name: "Laser Characterization System",
    type: "equipment",
    status: "available",
    location: "Dutton Lab - Room 105",
    description: "Advanced laser spectrum analysis",
    compatibleProjects: ["p2", "p4"],
  },
];

export const mockBookings: Booking[] = [
  {
    id: "b1",
    equipmentId: "2",
    equipmentName: "Photonic Probe Station",
    studentName: "Alice Johnson",
    studentEmail: "alice.johnson@ufl.edu",
    startTime: new Date(2025, 0, 1, 10, 0),
    endTime: new Date(2025, 0, 1, 12, 0),
    duration: 120,
    projectId: "p2",
    projectName: "Photonics Integration",
    purpose: "Testing new photonic circuits",
    status: "in-progress",
  },
  {
    id: "b2",
    equipmentId: "1",
    equipmentName: "Quantum Measurement System",
    studentName: "Bob Martinez",
    studentEmail: "bob.martinez@ufl.edu",
    startTime: new Date(2025, 0, 1, 14, 0),
    endTime: new Date(2025, 0, 1, 16, 30),
    duration: 150,
    projectId: "p1",
    projectName: "Quantum Computing Research",
    purpose: "Quantum state measurements",
    status: "scheduled",
  },
  {
    id: "b3",
    equipmentId: "3",
    equipmentName: "Robotic Arm Alpha",
    studentName: "Carol White",
    studentEmail: "carol.white@ufl.edu",
    startTime: new Date(2025, 0, 1, 9, 0),
    endTime: new Date(2025, 0, 1, 10, 30),
    duration: 90,
    projectId: "p4",
    projectName: "Material Characterization",
    purpose: "Automated sample preparation",
    status: "completed",
  },
  {
    id: "b4",
    equipmentId: "6",
    equipmentName: "Laser Characterization System",
    studentName: "David Chen",
    studentEmail: "david.chen@ufl.edu",
    startTime: new Date(2025, 0, 2, 13, 0),
    endTime: new Date(2025, 0, 2, 15, 0),
    duration: 120,
    projectId: "p2",
    projectName: "Photonics Integration",
    purpose: "Laser spectrum analysis",
    status: "scheduled",
  },
];
