-- =====================================================================================
-- 2026-08-08  SUPERSEDED — this migration is intentionally a NO-OP. Do not restore it.
--
-- This file once contained `DROP TABLE public.password_reset_tokens`. It was written on the
-- strength of a comment in supabase/config.toml claiming the table had already been dropped
-- in production. That claim was wrong. The table is live and holds 44 rows.
--
-- It was NEVER APPLIED, and the decision was reversed: the table stays. It is orphaned but
-- harmless — nothing in src/ reads it, manage-users does not touch it, and a dependency
-- check found no views, functions, triggers or foreign keys referencing it. Dropping it
-- gains nothing, and the old password-reset edge functions may still be deployed
-- server-side even though their source has been removed from this repo.
--
-- The body is emptied rather than the file deleted because the file is already committed and
-- an unapplied DROP sitting in supabase/migrations/ is a live hazard: anyone running
-- `supabase db push`, resetting a branch, or rebuilding an environment from this directory
-- would destroy production data that a deliberate decision chose to keep. If you would
-- rather it were gone entirely, `git rm` this file — that is safe, since it has never been
-- applied anywhere and appears in no migration ledger.
-- =====================================================================================

SELECT 1 WHERE false;  -- deliberately does nothing
