// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
    // PKCE, not the default 'implicit'.
    //
    // The app uses HashRouter, so it owns the URL fragment. An implicit-flow recovery link
    // comes back as "...#access_token=...&type=recovery", which the router would try to read
    // as a route and the login would break. PKCE returns "?code=..." in the QUERY string
    // instead, and supabase-js gives search params precedence when it looks for a callback,
    // so the two never collide. On load the client exchanges the code automatically and
    // fires onAuthStateChange('PASSWORD_RECOVERY').
    flowType: 'pkce',
  }
});